language: java
install:
- mvn -N io.takari:maven:wrapper
- ./mvnw install -DskipTests=true -Dmaven.javadoc.skip=true -B -V
services:
- mysql
before_install:
- sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('shr3793') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;" | mysql -u root
- sudo service mysql restart
- mysql -e 'CREATE DATABASE IF NOT EXISTS user_cloud'

